### ISSUE TITLE
not loading saved sessions properly

### ISSUE THREAD

**Issue by katchy3132** [jjw24/Flow.Launcher.Plugin.Putty#7]
I upgraded to 2.1.0 and now it seems that the plugin is passing the session name to Putty as the host to connect and not loading the session from putty. 

eg if I have  a session named "rack1" that is supposed to connect to root@1.2.3.4. it will say "unable to connect : rack1 host not found. It will open without problem from within putty itself .

**Comment by jjw24** [comment]
fixed with 2.1.1 release
